### ISSUE TITLE
Add option to disallow additional properties per default

### ISSUE THREAD

**Issue by johannesluedke** [interagent/committee#284]
It would be nice to be able to switch comittee in a mode where it not only checks that the payloads adhere to the schema, but that it also warns when there is more than the payload than specified. 
This could help to keep the api spec up to date and to not forget to adjust the spec when adding something to the payload.

**Comment by ota42y** [comment]
OpenAPI support `additionalProperties` (OpenAPI 3 use JSON Schema and JSON Schema support this option)
https://tools.ietf.org/html/draft-zyp-json-schema-00#page-9

When you set false to this property and there is more than the payload than specified, committee raise error.
You can show warning using `error_handler` and ignore error using `ignore_error` option.
(When use `ignore_error` option committee ignore all errors so please raise in `error_handler` method).

Please issue again if you would like to add it so that it can be done easily in the committee.

**Comment by johannesluedke** [comment]
@ota42y 
Well `additionalProperties` has to be added as a sibling next to each `properties`, so one has to not forget to add `additionalProperties:false` each time. The idea of this issue was to be able to switch on the effect of `additionalProperties:false` for everything at once.

**Comment by ota42y** [comment]
I am sorry that I didn't understand your intentions correctly...

I think when committee change OpenAPI definition, there will be a difference between the definition to be validated and the definition written in the file so we can't use other OpenAPI tools... (e.g. OpenAPI Generator)
I think if you don't want to forget to add it, it's a good idea to validate the definition file (like linter).
