### ISSUE TITLE
Validation of GET params

### ISSUE THREAD

**Issue by michaelsauter** [interagent/committee#97]
If I have a `GET` endpoint that takes a parameter of type integer, the validation fails, since the parameter is actually of type string. For `POST` endpoints, this problem does not exist since in the JSON payload, I can explicitly pass an integer. For GET, that's not possible. Is that true or am I missing something really obvious?

I had a look through the request validation code to see how it works but there's no immediate solution to the problem that comes to my mind. Any ideas? I guess somehow committee should allow a string that is only numbers as an integer?

**Comment by michaelsauter** [comment]
Or maybe this is more related to https://github.com/brandur/json_schema? Since that is what is only allowing an `Integer` class for the integer type ...

**Comment by geemus** [comment]
It may just be oversite, in our usage we pretty much only use params from body json, where they would be encoded as integers. I guess, that said, if it really is a string, maybe you should set the validation to either expect an integer or to accept both integer and string?

**Comment by michaelsauter** [comment]
Hmm. The issue is that I'd like to accept integers only, but that is not possible. Committee allows me to avoid param validation in the controller, and if I have to allow string, I need to manually convert it to integers ...

So that means you also use a body json for GET requests? I think most clients would probably assume the params are added to the query string.

**Comment by geemus** [comment]
I think we have largely avoided params for GET, and/or in those places where we do I think we may be failing to validate at this point (that is the state of things in some legacy places). It is a little awkward here in that json-schema is todo with validating json (which this isn't), so I could kind of go either way.

@brandur thoughts?

**Comment by brandur** [comment]
> So that means you also use a body json for GET requests? I think most clients would probably assume the params are added to the query string.

That's definitely one way to go! Although Roy Fielding himself has somewhat infamously [come out against the use of request bodies on `GET` actions](http://stackoverflow.com/a/983458).

Unfortunately, there's no clear answer on this one because there's a fundamental mismatch between two encoding schemes: JSON schema is designed to validate JSON which has non-string types and can therefore unlock some more powerful features, but `GET` parameters are encoded as `application/x-www-form-urlencoded` where all values are strings.

I'd suggest one of two things:

1. In definitions for `GET` endpoints, don't use the integer type, but rather a string, and then pair it with `format` to check that the input is indeed numeric. You'll have to do some basic parsing at your application level, but at least you'll have some basic validation that your input is what you expected.
2. Implement a simple middleware that sits on the stack above Committee and attempts to coerce query strings on GET requests into typed form. You should be able to store the newly coerced hash into `env`'s `rack.request.query_hash` key and have Committee pick it up.

The first option is probably better.

**Comment by michaelsauter** [comment]
Thanks for your input. We already went with (1) as a stop-gap solution. I guess we'll just have to stick to it.

**Comment by geemus** [comment]
@michaelsauter @brandur thanks for helping talk through it. Definitely too bad that there isn't more type information in query params, but it is what it is I guess. I hadn't considered format, that does sounds like probably the best available workaround.

**Comment by michaelsauter** [comment]
@geemus Hmm yes, but it falls down pretty quickly. E.g. if you actually want an integer between 9 and 47. That is not easy to do with a string format ;)

**Comment by geemus** [comment]
Yeah, very true. I guess another way around it is to make a POST alternative to the same route, and then types/formats fit more tightly. Awkward in it's own right, but using untyped stuff obviously has it's own issues.

**Comment by michaelsauter** [comment]
@brandur I came across this yet again and thought a little more about your alternative suggestion.

What do you think about the following suggestion (and would you be open to include a PR like this)?

1. Have another option for Committee called `coerce_query_params` (default false)
2. If true, after https://github.com/interagent/committee/blob/master/lib/committee/middleware/request_validation.rb#L23, one would try to read the defined keys/types of the link schema.
3. With those, the query params could be coerced and updated in `rack.request.query_hash`. Any exception would be treated as a validation error.
4. The request unpacking (currently in https://github.com/interagent/committee/blob/master/lib/committee/middleware/request_validation.rb#L16) should happen after this (I don't see why it couldn't be moved inside the condition?).
5. Then Committee would go on as usual.

I guess at least integer, float and boolean could be covered, which would already be quite nice as they are very common.

What do you think?

**Comment by brandur** [comment]
@michaelsauter This sounds like a pretty good plan to me. We'd need to be quite specific in the description of the option that because not everything is going to be cleanly coercable from text that the option only supports a subset of types (although I guess most JSON types are represented in your list except array, object, and null).

I'm happy to review such a PR if you're willing to assemble one.
